#!/usr/bin/env bash
# bundle_rbo.sh - Bundle multiple .rbo files into one

set -euo pipefail

OUTPUT="bundle.rbo"
FILES=()

while [[ $# -gt 0 ]]; do
  case "$1" in
    -o|--output)
      OUTPUT="$2"
      shift 2
      ;;
    *)
      FILES+=("$1")
      shift
      ;;
  esac
done

if [[ ${#FILES[@]} -eq 0 ]]; then
  echo "Usage: $0 <file1.rbo> <file2.rbo> ... [-o output.rbo]"
  exit 1
fi

echo "[bundle] Bundling ${#FILES[@]} files -> $OUTPUT"

# Create bundle header
cat > "$OUTPUT" <<'EOF'
# Rubolt Bundle
# Auto-generated by bundle_rbo.sh

EOF

# Append each file with separator
for f in "${FILES[@]}"; do
  if [[ ! -f "$f" ]]; then
    echo "Warning: File not found: $f"
    continue
  fi
  
  echo "[bundle] Adding $f"
  echo "" >> "$OUTPUT"
  echo "# ===== BEGIN: $f =====" >> "$OUTPUT"
  cat "$f" >> "$OUTPUT"
  echo "# ===== END: $f =====" >> "$OUTPUT"
  echo "" >> "$OUTPUT"
done

echo "[bundle] Bundle created: $OUTPUT"
