#!/usr/bin/env bash
# wrap_py_module.sh - Wrap Python modules for Rubolt compatibility

set -euo pipefail

if [[ $# -lt 2 ]]; then
  echo "Usage: $0 <module.py> <output_wrapper.rbo>"
  exit 1
fi

INPUT="$1"
OUTPUT="$2"

if [[ ! -f "$INPUT" ]]; then
  echo "Error: Module not found: $INPUT"
  exit 1
fi

MODULE_NAME=$(basename "$INPUT" .py)

echo "[wrap] Wrapping $INPUT -> $OUTPUT"

# Extract functions from Python module
FUNCS=$(grep -oP '^\s*def\s+\K\w+' "$INPUT" || echo "")

# Generate Rubolt wrapper
cat > "$OUTPUT" <<EOF
# Rubolt Wrapper for Python Module: $MODULE_NAME
# Auto-generated by wrap_py_module.sh

import python.$MODULE_NAME as _py_$MODULE_NAME

EOF

# Wrap each function
for func in $FUNCS; do
  cat >> "$OUTPUT" <<EOF
func ${func}(*args, **kwargs) {
    return _py_$MODULE_NAME.${func}(*args, **kwargs)
}

EOF
done

# Export all functions
echo -n "export " >> "$OUTPUT"
first=true
for func in $FUNCS; do
  if [[ "$first" = true ]]; then
    first=false
  else
    echo -n ", " >> "$OUTPUT"
  fi
  echo -n "$func" >> "$OUTPUT"
done
echo "" >> "$OUTPUT"

echo "[wrap] Wrapper created: $OUTPUT"
echo "[wrap] Wrapped functions: $FUNCS"
